version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: barber-postgres
    environment:
      POSTGRES_USER: barber
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barber
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
